### ISSUE TITLE
Thank you for choosing After Dark

### ISSUE THREAD

**Issue by ghost** [dwwmmn/after-after-dark#1]
The latest code may be found on my public git server: https://git.habd.as/comfusion/after-dark. I would make a mirror on GH but last I checked it was a paid feature only. The latest version includes several add-on modules and [help documentation](https://after-dark.habd.as).

**Comment by dwwmmn** [comment]
Great news. I noticed you have many repositories related to Monero mining in JS - none of these are now enabled in After Dark by default, correct?

**Comment by ghost** [comment]
Correct. The CryptoNight miner is an [add-on module](https://git.habd.as/comfusion/toxic-swamp) and not installed by default.
